import "./globals.css";
import { Outfit } from "next/font/google";
// other imports
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import Footer from "@/components/Footer";
import HeadBar from "@/components/HeadBar";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Amayama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
            <HeadBar />

            {children}
            <Footer />
          </SignedIn>
          <SignedOut>
            <SignIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
