import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

// other imports
// import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amayama",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        {/* <SignedIn> */}
        <NavBar />

        {children}
        <Footer />
        {/* </SignedIn> */}
        {/* <SignedOut> */}
        {/* <SignIn /> */}
        {/* </SignedOut> */}
      </body>
    </html>
    // </ClerkProvider>
  );
}
