import "./globals.css";
// import { Metadata } from "next";
import { Outfit } from "next/font/google";
// import { GlobalProvider } from "@/app/GlobalProvider";
// other imports
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import HeadBar from "@/components/HeadBar";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Amayama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
            {/* <NavBar /> */}
            {/* <GlobalProvider> */}
              <HeadBar />

              {children}
              <Footer />
            {/* </GlobalProvider> */}
          </SignedIn>
          <SignedOut>
            <SignIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
